// Generated by tools/build_pages.js
;(function () {
  var base = new URL('.', document.currentScript.src).href
  window.env = {
    PRODUCTION: 'true',
    API_URL: base + 'api',
    R2_URL: base + 'data.hyperfy.xyz',
    UPLOADS_TARGET: '',
    ENTITIES_TARGET: 'r2',
    DEFAULT_WORLD: "neue2dojo",
    AGORA_APP_ID: '',
    LIVEKIT_URL: '',
    SOCK: '',
    MODE: 'live',
    // mirrored hosts the client hard-codes (site/client-patches.js)
    CDN_URL: base + 'data.hyperfy.xyz',
    FONTS_URL: base + 'fonts.gstatic.com/',
    // this world (site/backend.js, site/overlay.js)
    WORLD_ID: "world-1194",
    MODES: [],
  }
})()
